EMAIL_ADDRESS = "jimmymccrab@gmail.com"
EMAIL_PASSWORD = "vlzsslubznjkhnlc"
PUSHOVER_USER_KEY = "ujzqf4h4cjv1piemk4da2j4sn2w281"
PUSHOVER_APP_TOKEN = "ancis8sn5ahu5wwq9r8ozasr2bf5u6"
TWELVE_DATA_KEY = "6207ee078aee4511aeac2cf670bf23f6"
